
@api = http://localhost:3000

POST {{api}}/tracking
Content-Type: application/json

{
    "latitude": "20.905743",
    "longitude": "-103.974921",
    "vehicleId": "65f89495d7a31a44ce738039"
}


###
GET {{api}}/tracking/65f891634327b8c0ea6b2c1b

###
DELETE {{api}}/tracking/65f891634327b8c0ea6b2c1b

###
POST {{api}}/tracking/vehicle/65f89495d7a31a44ce738039
Content-Type: application/json

{
    "filters": [
        {
            "field": "createdAt",
            "value": "2024-03-15, 2024-03-17",
            "filter": "between"
        }
    ],
    "objectsPerPage": 5,
    "page": 1
}
