@api = http://localhost:3000

GET {{api}}/vehicle

###
GET {{api}}/vehicle/65f78a7f0d4ffba05b60fda6

###
POST {{api}}/vehicle
Content-Type: application/json

{
    "plate": "62622",
    "economicNumber": "512561254",
    "vim": "WAUDH98E36A1439",
    "seats": 30,
    "insurance": "Conn-Kuhic",
    "insuranceNumber": "2215",
    "brand": "Kia",
    "model": "Rio",
    "year": 2005,
    "color": "Blue"
}

###
PUT {{api}}/vehicle/disabled/65f78b8a5ed2ffd1c4b6d763

###
PUT {{api}}/vehicle/65f792c04d5202c365de394d
Content-Type: application/json

{
    "plate": "999999999999999",
    "economicNumber": "512561254",
    "vim": "WAUDH98E36A1439",
    "seats": 20,
    "insurance": "Conn-Kuhic",
    "insuranceNumber": "2215",
    "brand": "Kia",
    "model": "Rio",
    "year": 2005,
    "color": "Blue",
    "alive": true
}


###
POST {{api}}/vehicle/search/seats/32