@api = http://localhost:3000

POST {{api}}/vehicle
Content-Type: application/json

{
    "filters": [
        {
            "field": "insurance",
            "value": "Conn",
            "filter": "startWith"
        }
    ],
    "objectsPerPage": 5,
    "page": 1
}

        # {
        #     "field": "color",
        #     "value": "Blue",
        #     "filter": "equals"
        # }

###
GET {{api}}/vehicle/65f78b8a5ed2ffd1c4b6d763

###
POST {{api}}/vehicle/new
Content-Type: application/json

{
    "plate": "558sjefe",
    "economicNumber": "219125554e5",
    "vim": "828232323",
    "seats": 15,
    "insurance": "Satterfield LLC",
    "insuranceNumber": "985555255",
    "brand": "Toyota",
    "model": "Corolla",
    "year": 2020,
    "color": "Black",
    "tracking": [
        "65f8912b4327b8c0ea6b2c19"
    ]
}

###
PUT {{api}}/vehicle/disabled/65f78b8a5ed2ffd1c4b6d763
Content-Type: application/json

{
    "alive": false
}

###
PUT {{api}}/vehicle/65f792c04d5202c365de394d
Content-Type: application/json

{
    "plate": "999999999999999",
    "economicNumber": "512561254",
    "vim": "WAUDH98E36A1439",
    "seats": 18,
    "insurance": "Conn-Kuhic",
    "insuranceNumber": "2215",
    "brand": "Kia",
    "model": "Rio",
    "year": 2005,
    "color": "Blue",
    "alive": true
}


###
POST {{api}}/vehicle/search/seats/32

###
GET {{api}}/vehicle/tracking/65f89495d7a31a44ce738039
